jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        warmup:
            # list of directories to scan searching for php classes to use when warming up the cache
            paths:
                included: [ "src/DTO", "src/Entity" ]
                excluded: []
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
