exclude_paths:
 - "/tests/*"
 - "/var/*"
 - "/vendor/*"
 - "/web/*"
engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "standards/ruleset-pmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
ratings:
  paths:
  - "**.php"
