sudo: false

jobs:
  include:
    - stage: "Unit tests & staging 1 deploy"
      language: php
      php: 7.2
      services:
        - mysql
      cache:
        yarn: true
        directories:
          - "$HOME/.composer/cache/files"
      env:
        - SYMFONY_VERSION="3.3.*" DB=mysql BUILD_ID=${TRAVIS_BRANCH}/${TRAVIS_COMMIT:0:7}/${TRAVIS_BUILD_NUMBER}
      before-install:
        - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - composer self-update
      install:
        - composer install
        - yarn install
        - yarn build
        - bin/setBuildId.sh ${BUILD_ID}
        - bin/console lint:yaml app/config
        - bin/console lint:twig app/Resources/views
        - bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
        - bin/console doctrine:database:create --no-interaction --env=test
        - bin/console doctrine:schema:create --no-interaction --env=test
        - bin/console doctrine:fixtures:load --no-interaction --env=test
      script:
        - vendor/bin/phpunit
        - cat var/logs/test.log | grep -Ev 'NotFoundHttpException|MethodNotAllowedHttpException|BadRequestHttpException'
      deploy:
        provider: heroku
        api_key: $HEROKU_AUTH_TOKEN
        app: $HEROKU_APP_STAG1
        skip_cleanup: true
        run:
          - "bin/loadTestDB.sh"
        on:
          all_branches: true

    - stage: "Staging 1 : e2e tests"
      language: python
      python: 2.7
      env:
        - BUILD_ID=${TRAVIS_BRANCH}/${TRAVIS_COMMIT:0:7}/${TRAVIS_BUILD_NUMBER}
      install:
        - pip install -r tests/RF/requirements.txt
        - mv tests/RF/Common/Conf/mail.txt.dist tests/RF/Common/Conf/mail.txt
        - bin/dumpDB.sh -d ${DATABASE_URL_STAG1} dump-stag1.sql
      script:
        - pabot --processes 5 -e EDIT -v BUILD_ID:${BUILD_ID} -v ENV:PROD -v WEB_HOST:https://${HEROKU_APP_STAG1}.herokuapp.com -v GRID:True -v GRID_USER:${GRID_USER} -v GRID_TOKEN:${GRID_TOKEN} tests/RF

notifications:
  slack:
    secure: VoxTm0ES0rknLxynTfwWrnv4o9WBKD3aNKVCXYeXmsvhgsuWj9XVoKXGQc9xFrvYFmH/Ymd3sVhyVYOYDGc6FprY6UEpkwhpAWKj8AM+vUIC71doAhprMwns1jLCWFT/AYeqsRjKX42bg3Y7ml9ChdiPU4FDPRpnvVAYz4MR1XTHuWPz6g7TWahyU4WAIxuo+Is6iKLJwuISNysf2+zv2PjUCpGyJYByEBbgcqIn9ZoWIYgcT2eDxd4zULipt5hiY3LRrkDuw0rhVkD0QjN3dhFejDJ3xrjckjDuKOJ/q5HiZwMZ8F2dlRB4rFKXAWqUvUzYXyltIugnHuMg8EJb7CebLEPfCW1HYxDUTM4ZligeHndT9zTl7xZGz7+BTX/vaaefYZTzTdNMIpqU4f5kAxJS0fxev/nWmreBQ6o67cI9UYZHrM7/9kOD8uQG7eXAbJY/1RGrSkMdTc3lLIiYfQosZhJVdp60G9UjPqI8kRWoFENm3/5zypLpVrBrJobcr+z+hcD99ZOsXSAwpPgSVyMmEq3ijKJOP9+KnkJi5/BEAvhnxS6CelCFyqb+zKPgox+jOdIbxBbRwlxTV0InObdedGGL5/wfo/+WEKVd9lcTz+kJFV2EEoCRmQjPb3aC7I1G4J1mjigkL2WDI7J7oNHtFxjWJ5mXNmuWEovTkyg=
