ARG  CIR_BUILD_APP_IMG=builder-app
ARG  CIR_BUILD_WEB_IMG=builder-web
ARG  CIR_TAG=latest

FROM node:9 as builder-web

LABEL maintainer="soubirou@yahoo.fr"
LABEL description="Builder docker container for web assets of ci-report project"
LABEL website="https://www.ci-report.io"

WORKDIR /symfony

COPY webpack.config.js .
COPY assets assets
COPY package.json .
COPY yarn.lock .

RUN mkdir /symfony/public
RUN yarn install && yarn run encore production


FROM ${CIR_BUILD_APP_IMG}:${CIR_TAG} as builder-app-tag
FROM ${CIR_BUILD_WEB_IMG}:${CIR_TAG} as builder-web-tag

FROM nginx:latest as ci-report-web

LABEL maintainer="soubirou@yahoo.fr"
LABEL description="nginx docker container of ci-report project"
LABEL website="https://www.ci-report.io"

COPY docker/nginx/default.conf /etc/nginx/conf.d/
RUN mkdir -p /symfony/public
COPY assets/static /symfony/public
COPY --from=builder-app-tag /symfony/public/bundles /symfony/public/bundles
COPY --from=builder-web-tag /symfony/public/build /symfony/public/build
