ARG  CIR_BUILD_APP_IMG=builder-app
ARG  CIR_TAG=latest

FROM php:7.2-fpm as builder-app

LABEL maintainer="soubirou@yahoo.fr"
LABEL description="Builder docker container for php application of ci-report project"
LABEL website="https://www.ci-report.io"

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libicu-dev \
    libpng-dev \
    libxml2-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-install gd \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install opcache \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install xml \
    && docker-php-ext-install zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /symfony

COPY composer.json .
COPY composer.lock .
COPY symfony.lock .
COPY bin/console bin/console
COPY config config
RUN find config -name '*dev*' -exec rm -rf {} +
RUN find config -name '*test*' -exec rm -rf {} +
COPY public/index.php public/index.php
COPY src src
RUN rm -rf src/DataFixtures
COPY templates templates
COPY translations translations
RUN mkdir var

ENV APP_DEBUG=0 \
    APP_ENV=prod \
    APP_SECRET=253307d07e2b0b2aab453f89e31111ba \
    DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name \
    LOG_PATH=php://stderr \
    MAILER_SENDER=ci-report.sender@example.com \
    MAILER_URL=null://localhost \
    WEB_HOST=http://127.0.0.1:8000

RUN composer install --no-dev --optimize-autoloader && bin/console assets:install public


FROM ${CIR_BUILD_APP_IMG}:${CIR_TAG} as builder-app-tag

FROM php:7.2-fpm as ci-report-app

LABEL maintainer="soubirou@yahoo.fr"
LABEL description="php-fpm docker container of ci-report project"
LABEL website="https://www.ci-report.io"

RUN apt-get update && apt-get install -y \
    libicu-dev \
    libpng-dev \
    libxml2-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-install gd \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install opcache \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install xml \
    && docker-php-ext-install zip

COPY docker/php-fpm/opcache.ini $PHP_INI_DIR/conf.d/

WORKDIR /symfony

COPY --from=builder-app-tag /symfony/composer.json .
COPY --from=builder-app-tag /symfony/config config
COPY --from=builder-app-tag /symfony/public/index.php public/index.php
COPY --from=builder-app-tag /symfony/src src
COPY --from=builder-app-tag /symfony/templates templates
COPY --from=builder-app-tag /symfony/translations translations
COPY --from=builder-app-tag /symfony/var/cache var/cache
COPY --from=builder-app-tag /symfony/vendor vendor

RUN chown www-data:www-data var/cache/prod/jms_serializer

ENV APP_DEBUG=0 \
    APP_ENV=prod \
    APP_SECRET=253307d07e2b0b2aab453f89e31111ba \
    DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name \
    MAILER_SENDER=ci-report.sender@example.com \
    MAILER_URL=null://localhost \
    WEB_HOST=http://127.0.0.1:8080
