<?php
/**
 * Copyright (c) 2017 Francois-Xavier Soubirou.
 *
 * This file is part of ci-report.
 *
 * ci-report is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ci-report is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ci-report. If not, see <http://www.gnu.org/licenses/>.
 */
namespace AppBundle\Repository;

use AppBundle\Entity\Campaign;
use AppBundle\Entity\Suite;
use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * SuiteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiteRepository extends SortableRepository
{
    /**
     * Get all suites for a campaign.
     *
     * @param Campaign $campaign The campaign.
     *
     * @return array List of suites.
     */
    public function findSuitesByCampaign(Campaign $campaign)
    {
        $qb = $this->createQueryBuilder('s')
            ->innerJoin('s.campaign', 'c')
            ->where('c.id = :campaignId')
            ->setParameter('campaignId', $campaign->getId())
            ->orderBy('s.datetimeSuite', 'DESC', 's.position', 'DESC');

        $result = $qb->getQuery()->getResult();

        return $result;
    }

    /**
     * Get a suite for a campaign and its refId.
     *
     * @param Campaign $campaign The campaign.
     * @param int      $refId    RefId of the suite in the campain.
     *
     * @return array List of suites.
     */
    public function findSuiteByCampaignAndRefId(Campaign $campaign, $refId)
    {
        $position = $refId - 1;

        $qb = $this->createQueryBuilder('s')
            ->innerJoin('s.campaign', 'c')
            ->where('c.id = :campaignId')
            ->andWhere('s.position = :position')
            ->setParameter('campaignId', $campaign->getId())
            ->setParameter('position', $position);

        $result = $qb->getQuery()->getOneOrNullResult();

        return $result;
    }

    /**
     * Get previous suite for a suite.
     *
     * @param Campaign $campaign The campaign.
     * @param Suite    $suite    The suite.
     *
     * @return Suite.
     */
    public function findPrevSuiteByCampaign(Campaign $campaign, Suite $suite)
    {
        $qb = $this->createQueryBuilder('s')
            ->innerJoin('s.campaign', 'c')
            ->where('c.id = :campaignId')
            ->andWhere('s.position < :position')
            ->setParameter('campaignId', $campaign->getId())
            ->setParameter('position', $suite->getPosition())
            ->orderBy('s.position', 'DESC')
            ->setMaxResults(1);

        $result = $qb->getQuery()->getOneOrNullResult();

        return $result;
    }

    /**
     * Get next campaign for a campaign.
     *
     * @param Campaign $campaign The campaign.
     * @param Suite    $suite    The suite.
     *
     * @return Suite.
     */
    public function findNextSuiteByCampaign(Campaign $campaign, Suite $suite)
    {
        $qb = $this->createQueryBuilder('s')
            ->innerJoin('s.campaign', 'c')
            ->where('c.id = :campaignId')
            ->andWhere('s.position > :position')
            ->setParameter('campaignId', $campaign->getId())
            ->setParameter('position', $suite->getPosition())
            ->orderBy('s.position', 'ASC')
            ->setMaxResults(1);

        $result = $qb->getQuery()->getOneOrNullResult();

        return $result;
    }
}
