<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Suite;
use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * SuiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends SortableRepository
{
    /**
     * Get all tests for a suite.
     *
     * @param Suite $suite The suite.
     *
     * @return Array List of tests.
     */
    public function findTestsBySuite(Suite $suite)
    {
        $qb = $this->createQueryBuilder('t')
            ->innerJoin('t.suite', 's')
            ->where('s.id = :suiteId')
            ->setParameter('suiteId', $suite->getId())
            ->orderBy('t.package', 'ASC', 't.className', 'ASC', 't.name', 'ASC', 't.position', 'ASC');

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
