kind: "Service"
apiVersion: "v1"
metadata:
   labels:
      app: ci-report-ext-db
      name: ci-report-ext-db-staging
   name: "external-mysql-service"
spec:
   ports:
      -
         name: "mysql"
         protocol: "TCP"
         port: 3306
         targetPort: 3306
         nodePort: 0
selector: {}
